### ISSUE TITLE
KeyError: 'message' analyzing confluence

### ISSUE THREAD

**Issue by sanacl** [MetricsGrimoire/MediaWikiAnalysis#3]
[2015-11-03 13:12:35] /usr/local/bin/confluence_analysis.py -u "root" -p "***" -d "quan_confluence_hawq_6719" "https://cwiki.apache.org
/confluence/" "HAWQ" >> /home/owl/dashboards/pivotal-hawq/log/launch_confluence.log 2>&1
Fetching contents from 0 to 24
DBG: [03/Nov/2015-13:12:37] Confluence content/search method called: https://cwiki.apache.org/confluence//rest/api/content/search?li
mit=25&expand=history%2Cspace&cql=space+%3D+HAWQ+and+lastmodified+%3E%3D+%222015-11-02+21%3A58%22+order+by+lastModified
Fetching versions of 61321877
DBG: [03/Nov/2015-13:12:37] Fetching version : 61321877:10
DBG: [03/Nov/2015-13:12:37] Confluence content/61321877 method called: https://cwiki.apache.org/confluence//rest/api/content/61321877?status=historical&version=10
Fetching versions of 61326707
DBG: [03/Nov/2015-13:12:37] Fetching version : 61326707:1
DBG: [03/Nov/2015-13:12:38] Confluence content/61326707 method called: https://cwiki.apache.org/confluence//rest/api/content/61326707?status=historical&version=1
DBG: [03/Nov/2015-13:12:38] Fetching version : 61326707:2
DBG: [03/Nov/2015-13:12:39] Confluence content/61326707 method called: https://cwiki.apache.org/confluence//rest/api/content/61326707?status=historical&version=2
DBG: [03/Nov/2015-13:12:39] Fetching version : 61326707:3
DBG: [03/Nov/2015-13:12:40] Confluence content/61326707 method called: https://cwiki.apache.org/confluence//rest/api/content/61326707?status=historical&version=3
DBG: [03/Nov/2015-13:12:40] Fetching version : 61326707:4
DBG: [03/Nov/2015-13:12:41] Confluence content/61326707 method called: https://cwiki.apache.org/confluence//rest/api/content/61326707?status=historical&version=4
Traceback (most recent call last):
  File "/usr/local/bin/confluence_analysis.py", line 96, in <module>
    main()
  File "/usr/local/bin/confluence_analysis.py", line 45, in main
    for content in backend.fetch(args.space, last_activity):
  File "/usr/local/lib/python2.7/dist-packages/wikianalysis/confluence.py", line 151, in fetch
    versions = self.__fetch_versions(content.wikipage_id, from_version)
  File "/usr/local/lib/python2.7/dist-packages/wikianalysis/confluence.py", line 191, in __fetch_versions
    version = self.__parse_content_version(result)
  File "/usr/local/lib/python2.7/dist-packages/wikianalysis/confluence.py", line 217, in __parse_content_version
    message = raw_version['version']['message']
KeyError: 'message'

**Comment by sanacl** [comment]
I couldn't reproduce it with latest version. SOrry for the noise
